const elements = [
    { number: 1, symbol: 'H', nameJP: '水素', complexity: 1 },
    { number: 2, symbol: 'He', nameJP: 'ヘリウム', complexity: 2 },
    { number: 3, symbol: 'Li', nameJP: 'リチウム', complexity: 2 },
    { number: 4, symbol: 'Be', nameJP: 'ベリリウム', complexity: 2 },
    { number: 5, symbol: 'B', nameJP: 'ホウ素', complexity: 1 },
    { number: 6, symbol: 'C', nameJP: '炭素', complexity: 1 },
    { number: 7, symbol: 'N', nameJP: '窒素', complexity: 1 },
    { number: 8, symbol: 'O', nameJP: '酸素', complexity: 1 },
    { number: 9, symbol: 'F', nameJP: 'フッ素', complexity: 1 },
    { number: 10, symbol: 'Ne', nameJP: 'ネオン', complexity: 2 },
    { number: 11, symbol: 'Na', nameJP: 'ナトリウム', complexity: 2 },
    { number: 12, symbol: 'Mg', nameJP: 'マグネシウム', complexity: 2 },
    { number: 13, symbol: 'Al', nameJP: 'アルミニウム', complexity: 2 },
    { number: 14, symbol: 'Si', nameJP: 'ケイ素', complexity: 2 },
    { number: 15, symbol: 'P', nameJP: 'リン', complexity: 1 },
    { number: 16, symbol: 'S', nameJP: '硫黄', complexity: 1 },
    { number: 17, symbol: 'Cl', nameJP: '塩素', complexity: 2 },
    { number: 18, symbol: 'Ar', nameJP: 'アルゴン', complexity: 2 },
    { number: 19, symbol: 'K', nameJP: 'カリウム', complexity: 1 },
    { number: 20, symbol: 'Ca', nameJP: 'カルシウム', complexity: 2 },
    { number: 26, symbol: 'Fe', nameJP: '鉄', complexity: 2 },
    { number: 29, symbol: 'Cu', nameJP: '銅', complexity: 2 },
    { number: 30, symbol: 'Zn', nameJP: '亜鉛', complexity: 2 },
    { number: 47, symbol: 'Ag', nameJP: '銀', complexity: 2 },
    { number: 79, symbol: 'Au', nameJP: '金', complexity: 2 }
];
