const elements = [
    { number: 1, symbol: 'H', nameJP: '水素', nameCN: '氢', tricky: ['He', 'Hy', 'Ho'] },
    { number: 2, symbol: 'He', nameJP: 'ヘリウム', nameCN: '氦', tricky: ['H', 'Hu', 'El'] },
    { number: 3, symbol: 'Li', nameJP: 'リチウム', nameCN: '锂', tricky: ['L', 'La', 'Lu'] },
    { number: 4, symbol: 'Be', nameJP: 'ベリリウム', nameCN: '铍', tricky: ['B', 'Br', 'Bi'] },
    { number: 5, symbol: 'B', nameJP: 'ホウ素', nameCN: '硼', tricky: ['Be', 'Bo', 'Br'] },
    { number: 6, symbol: 'C', nameJP: '炭素', nameCN: '碳', tricky: ['Ca', 'Co', 'Cr'] },
    { number: 7, symbol: 'N', nameJP: '窒素', nameCN: '氮', tricky: ['Ni', 'Na', 'No'] },
    { number: 8, symbol: 'O', nameJP: '酸素', nameCN: '氧', tricky: ['Os', 'Ox', 'On'] },
    { number: 9, symbol: 'F', nameJP: 'フッ素', nameCN: '氟', tricky: ['Fe', 'Fl', 'Fu'] },
    { number: 10, symbol: 'Ne', nameJP: 'ネオン', nameCN: '氖', tricky: ['N', 'Ni', 'No'] },
    { number: 11, symbol: 'Na', nameJP: 'ナトリウム', nameCN: '钠', tricky: ['N', 'S', 'So'] },
    { number: 12, symbol: 'Mg', nameJP: 'マグネシウム', nameCN: '镁', tricky: ['Mn', 'Ma', 'Ag'] },
    { number: 13, symbol: 'Al', nameJP: 'アルミニウム', nameCN: '铝', tricky: ['A', 'Am', 'Au'] },
    { number: 14, symbol: 'Si', nameJP: 'ケイ素', nameCN: '硅', tricky: ['S', 'Li', 'So'] },
    { number: 15, symbol: 'P', nameJP: 'リン', nameCN: '磷', tricky: ['Ph', 'K', 'Po'] },
    { number: 16, symbol: 'S', nameJP: '硫黄', nameCN: '硫', tricky: ['Si', 'Su', 'Sa'] },
    { number: 17, symbol: 'Cl', nameJP: '塩素', nameCN: '氯', tricky: ['C', 'Ci', 'Co'] },
    { number: 18, symbol: 'Ar', nameJP: 'アルゴン', nameCN: '氩', tricky: ['A', 'Ag', 'Au'] },
    { number: 19, symbol: 'K', nameJP: 'カリウム', nameCN: '钾', tricky: ['Ka', 'P', 'Ko'] },
    { number: 20, symbol: 'Ca', nameJP: 'カルシウム', nameCN: '钙', tricky: ['Ka', 'K', 'C'] },
    { number: 26, symbol: 'Fe', nameJP: '鉄', nameCN: '铁', tricky: ['F', 'Ir', 'Te'] },
    { number: 47, symbol: 'Ag', nameJP: '銀', nameCN: '银', tricky: ['Si', 'S', 'Au', 'G'] },
    { number: 29, symbol: 'Cu', nameJP: '銅', nameCN: '铜', tricky: ['C', 'Co', 'Cr', 'Do'] },
    { number: 30, symbol: 'Zn', nameJP: '亜鉛', nameCN: '锌', tricky: ['Z', 'Zi', 'An'] },
    { number: 56, symbol: 'Ba', nameJP: 'バリウム', nameCN: '钡', tricky: ['B', 'Be', 'Br'] }
];
